# Generated by Django 2.2.10 on 2020-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('reported_on', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=40)),
                ('notes', models.TextField()),
            ],
        ),
    ]
