# Generated by Django 2.2.10 on 2020-09-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='state',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
