# Generated by Django 2.2.10 on 2020-09-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid', '0002_patientinfo_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
