# Generated by Django 2.2.10 on 2020-09-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Covid', '0003_auto_20200913_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='statsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
